"""
gcs_overlay.py
--------------
Overlay a GCS wireframe (generated by gcs_geometry) on the user's existing
composite coronagraph plot created by `create_single_diff_image(ax, time_str)`.

The overlay uses SunPy's coordinate frames to project 3D HGS points to
Helioprojective coordinates *with the LASCO map's observer*, then converts
arcsec -> Rsun -> pixels using the LASCO scale embedded in the user's composite.
"""
from dataclasses import dataclass, asdict
from typing import Dict, List, Tuple, Optional
import sys
import numpy as np
import matplotlib.pyplot as plt
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.time import Time

# We import only our minimal geometry helper
from .gcs_geometry import GCSParams, sample_gcs_wireframe_points

# SunPy frames imports are inside functions to avoid import-time issues if SunPy is not present.
def _to_hpc_arcsec_for_lasco(lasco_map, pts_hgs: np.ndarray, obstime: Time):
    """
    Convert Nx3 array of HGS Cartesian (Rsun) points to HPC arcsec for the LASCO observer.
    """
    import numpy as np
    from sunpy.coordinates import frames

    X, Y, Z = pts_hgs[:,0], pts_hgs[:,1], pts_hgs[:,2]
    r = np.sqrt(X*X + Y*Y + Z*Z)

    # Convert to spherical (lon, lat) in HGS
    lon = np.arctan2(Y, X) * u.rad
    lat = np.arcsin(Z / np.where(r>0, r, 1.0)) * u.rad
    radius = r * u.R_sun

    hgs = SkyCoord(lon=lon, lat=lat, radius=radius,
                   frame=frames.HeliographicStonyhurst,
                   obstime=obstime)

    # Transform to HPC using LASCO map's observer and obstime
    hpc = hgs.transform_to(
        frames.Helioprojective(
            observer=lasco_map.observer_coordinate, 
            obstime=lasco_map.date
        )
    )
    # hpc.Tx, hpc.Ty are in arcsec
    x_arcsec = hpc.Tx.to_value(u.arcsec)
    y_arcsec = hpc.Ty.to_value(u.arcsec)
    return x_arcsec, y_arcsec

def _arcsec_to_pixels_using_lasco_scale(x_arcsec: np.ndarray, y_arcsec: np.ndarray, lasco_map, p_lasco: Dict):
    """
    Convert HPC arcsec -> Rsun fraction (using LASCO's apparent solar radius) -> pixels
    relative to composite extent centered at (0,0).
    """
    rsun_arcsec = lasco_map.rsun_obs.to_value(u.arcsec)
    xr = x_arcsec / rsun_arcsec   # in Rsun
    yr = y_arcsec / rsun_arcsec
    scale = p_lasco['px_per_rsun']  # pixels per Rsun in the composite
    xp = xr * scale
    yp = yr * scale
    return xp, yp

def overlay_gcs_wireframe_on_axes(
    ax,
    lasco_map,
    p_lasco: Dict,
    gcs_params: GCSParams,
    obstime_str: str,
    n_parallels: int = 8,
    n_meridians: int = 12,
    color: str = 'white',
    color_legs: Optional[str] = None,
    lw: float = 1.0,
    alpha: float = 0.8,
    include_legs: bool = True,
    depth_shade: bool = False,
    alpha_near: float = 1.0,
    alpha_far: float = 0.3,
    alpha_far_legs: Optional[float] = None,
    leg_depth_from_joint: bool = True,
) -> Dict[str, List[np.ndarray]]:
    """
    Core overlay function to draw the wireframe given LASCO map + scale (from the composite).
    Returns the pixel polylines used (useful for debugging or saving).
    """
    # Sample 3D HGS points (Rsun)
    obstime = Time(obstime_str)

    wire = sample_gcs_wireframe_points(
        gcs_params,
        obstime=obstime,
        n_parallels=n_parallels,
        n_meridians=n_meridians,
        include_legs=include_legs,
    )

    legend_label = gcs_params.legend_label()
    legend_assigned = False

    polylines_px = {"parallels": [], "meridians": [], "legs": []}

    # 観測者（LASCO）の HGS 単位ベクトル o_hat（Sun→Observer）
    from sunpy.coordinates import frames
    obs_hgs = lasco_map.observer_coordinate.transform_to(
        frames.HeliographicStonyhurst(obstime=lasco_map.date)
    )
    import numpy as _np
    olon = obs_hgs.lon.to_value(u.rad); olat = obs_hgs.lat.to_value(u.rad)
    o_hat = _np.array([_np.cos(olat)*_np.cos(olon),
                       _np.cos(olat)*_np.sin(olon),
                       _np.sin(olat)], dtype=float)

    # Helper to project and draw
    from matplotlib.collections import LineCollection
    from matplotlib.colors import to_rgba
    def _project_and_draw(curves: List[np.ndarray], zorder: int, override_color: Optional[str] = None, is_legs: bool = False):
        nonlocal legend_assigned
        out: List[np.ndarray] = []
        for pts in curves:
            xa, ya = _to_hpc_arcsec_for_lasco(lasco_map, pts, obstime)
            xp, yp = _arcsec_to_pixels_using_lasco_scale(xa, ya, lasco_map, p_lasco)
            label = legend_label if (legend_label and not legend_assigned) else None
            
            use_color = override_color or color
            if not depth_shade:
                line_handles = ax.plot(xp, yp, color=use_color, lw=lw, alpha=alpha, zorder=zorder, label=label)
            else:
                # --- LOS 深度で alpha を連続変化 ---
                d = pts @ o_hat                   # Sun→Obs 方向成分（Rsun）
                dm = 0.5 * (d[:-1] + d[1:])       # 線分中点の深度
                if is_legs and leg_depth_from_joint:
                    # 脚：トーラス接続点（半径の大きい端）を基準に相対深度でフェード
                    import numpy as _np
                    radii = _np.sqrt((_np.asarray(pts) ** 2).sum(axis=1))
                    end0, end1 = 0, len(pts) - 1
                    joint_idx = int(end0 if radii[end0] >= radii[end1] else end1)
                    d0 = d[joint_idx]
                    rel = _np.abs(dm - d0)                 # 接続点からの離れ具合
                    rmax = rel.max() if rel.size and rel.max() > 0 else 1.0
                    w = 1.0 - (rel / rmax)                 # 接続点が 1.0, 遠ざかるほど 0.0
                else:
                    dmin, dmax = dm.min(), dm.max()
                    rng = (dmax - dmin) if (dmax > dmin) else 1.0
                    w = (dm - dmin) / rng                  # 0..1
                afar = (alpha_far_legs if (is_legs and alpha_far_legs is not None) else alpha_far)
                alphas = alpha_far + (alpha_near - afar) * w
                # 線分集合を作成
                import numpy as _np
                segs = _np.stack(
                    [_np.column_stack([xp[:-1], yp[:-1]]), _np.column_stack([xp[1:], yp[1:]])],
                    axis=1,
                )
                base = to_rgba(use_color)
                cols = [(base[0], base[1], base[2], float(a)) for a in alphas]
                lc = LineCollection(segs, colors=cols, linewidths=lw, zorder=zorder, label=label)
                ax.add_collection(lc)
                line_handles = [lc]
            if label and line_handles:
                legend_assigned = True
            out.append(np.column_stack([xp, yp]))
        return out
     
    polylines_px["parallels"] = _project_and_draw(wire["parallels"], zorder=5, override_color=None, is_legs=False)
    polylines_px["meridians"] = _project_and_draw(wire["meridians"], zorder=5, override_color=None, is_legs=False)
    if include_legs and len(wire["legs"])>0:
        polylines_px["legs"] = _project_and_draw(wire["legs"], zorder=6, override_color=(color_legs or color), is_legs=True)

    if legend_assigned:
        handles, labels = ax.get_legend_handles_labels()
        if labels:
            ax.legend(handles, labels)

    return polylines_px

def overlay_gcs_on_composite(
    ax,
    target_time_str: str,
    gcs_params: GCSParams,
    n_parallels: int = 8,
    n_meridians: int = 12,
    color: str = 'white',
    color_legs: Optional[str] = None,
    lw: float = 1.0,
    alpha: float = 0.8,
    include_legs: bool = True,
    depth_shade: bool = False,
    alpha_near: float = 1.0,
    alpha_far: float = 0.3,
    alpha_far_legs: Optional[float] = None,
    leg_depth_from_joint: bool = True,
    auto_h_apex: bool = False,
    h_bounds: Tuple[float, float] = (1.6, 6.0),
    pa_band_deg: float = 7.0,
    auto_lonlat: bool = False,
    lon_bounds: Tuple[float, float] = (-90.0, 90.0), # (引数は後方互換性のため残す)
    lat_bounds: Tuple[float, float] = (-60.0, 60.0), # (同上)
    coarse_step_deg: float = 5.0, # (同上)
    refine_step_deg: float = 1.0, # (同上)
    refine_iters: int = 2, # (同上)
) -> dict:
    """
    Convenience function:
      - Calls user's create_single_diff_image(ax, target_time_str)
      - Overlays the GCS wireframe using LASCO geometry from that composite
      - Returns a dict with:
          {
            'base': <return of create_single_diff_image>,
            'polylines': <pixel space polylines dict>,
            'gcs_params': <final GCSParams used>
          }
    """
    # Import lazily to avoid pulling user config on import
    from integrated_analysis import create_single_diff_image

    # Patch Horizons lookup to tolerate offline execution (no network access)
    if not hasattr(overlay_gcs_on_composite, "_horizons_patched"):
        from sunpy.coordinates import ephemeris, frames
        from requests.exceptions import RequestException

        original_get_horizons = ephemeris.get_horizons_coord
        def _get_horizons_with_fallback(target, obstime, *args, **kwargs):
            try:
                return original_get_horizons(target, obstime, *args, **kwargs)
            except RequestException:
                pass
            except Exception as exc:
                if "Name or service not known" not in str(exc):
                    raise
            target_upper = str(target).upper()
            if target_upper == 'SOHO':
                return SkyCoord(
                    lon=0.0 * u.deg, lat=0.0 * u.deg, radius=1.0 * u.AU,
                    frame=frames.HeliographicStonyhurst,
                    obstime=obstime, observer='earth',
                )
            return original_get_horizons(target, obstime, *args, **kwargs)
        ephemeris.get_horizons_coord = _get_horizons_with_fallback
        overlay_gcs_on_composite._horizons_patched = True

    # 1. ユーザー提供の関数でベース画像を作成
    base_info = create_single_diff_image(ax, target_time_str)
    lasco_map = base_info.get('lasco_map')
    p_lasco = base_info.get('params_lasco')
    
    # この関数内で更新していくGCSパラメータの作業用コピーを作成
    params_to_use = gcs_params

    # 2. h_apex 自動フィット（変更なし）
    if auto_h_apex and (lasco_map is not None):
        # ... (この部分はご提示のコードから変更ありません) ...
        # (h_apexを二分法で探索するロジック)
        try:
            pa0 = _nose_pa_deg_from_lonlat(lasco_map, params_to_use.lon_deg, params_to_use.lat_deg)
            pa_list = np.linspace(pa0 - pa_band_deg, pa0 + pa_band_deg, 7)
            r_obs_list: List[float] = []
            for pa in pa_list:
                r_rsun, I = _sample_radial_profile_along_pa(lasco_map, pa)
                r_val = _find_front_radius_rsun(r_rsun, I, smooth=7)
                if r_val is not None and np.isfinite(float(r_val)):
                    r_obs_list.append(float(r_val))
            
            if r_obs_list:
                r_obs_rsun = float(np.median(r_obs_list))
                rsun_arc = lasco_map.rsun_obs.to_value(u.arcsec)
                r_obs_arc = r_obs_rsun * rsun_arc
                lo, hi = h_bounds
                for _ in range(24):
                    mid = 0.5 * (lo + hi)
                    r_mid_arc = _project_apex_radius_arcsec(lasco_map, params_to_use, mid)
                    if r_mid_arc < r_obs_arc:
                        lo = mid
                    else:
                        hi = mid
                h_best = 0.5 * (lo + hi)
                print(f"\nAuto-fitting h_apex: {params_to_use.h_apex:.2f} -> {h_best:.2f} Rsun")
                params_to_use = params_to_use.__class__(**{**asdict(params_to_use), "h_apex": h_best})
        except Exception as e:
            print(f"[WARN] auto_h_apex failed: {e}")

    # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
    # 3. lon/lat 自動フィット (グリッドサーチからシンプルな直接変換方式に変更)
    # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
    if auto_lonlat and (lasco_map is not None):
        try:
            print("\nAttempting to auto-determine lon/lat from CME Position Angle...")
            
            # 3a. 画像からCME正面の位置角(PA)を検出
            pa_auto, _ = _detect_nose_pa_and_radius(lasco_map)
            
            if pa_auto is not None and np.isfinite(pa_auto):
                # 3b. 検出したPAをHGS座標系の(lon, lat)に変換
                lon_auto, lat_auto = pa_to_hgs_lonlat(pa_auto, lasco_map)
                
                print(f"  > Detected PA: {pa_auto:.1f} deg")
                print(f"  > Converted to HGS: lon={lon_auto:.1f} deg, lat={lat_auto:.1f} deg")
                
                # 3c. パラメータを自動計算した値で上書き
                params_to_use = params_to_use.__class__(**{
                    **asdict(params_to_use), 
                    "lon_deg": lon_auto, 
                    "lat_deg": lat_auto
                })
            else:
                print("  > Auto-determination failed: Could not detect a valid PA from the image.")

        except Exception as e:
            print(f"  > Auto-determination failed. Using provided values (lon={gcs_params.lon_deg}, lat={gcs_params.lat_deg}).")
            print(f"    Error details: {e}")

    # 4. 最終的なパラメータを使ってワイヤーフレームを描画
    polylines = overlay_gcs_wireframe_on_axes(
        ax, lasco_map, p_lasco, params_to_use, obstime_str=target_time_str,
        n_parallels=n_parallels, n_meridians=n_meridians,
        color=color, color_legs=color_legs, lw=lw, alpha=alpha, include_legs=include_legs,
        depth_shade=depth_shade, alpha_near=alpha_near, alpha_far=alpha_far, leg_depth_from_joint=leg_depth_from_joint
    )

    # 5. 結果を返却
    return {
        'base': base_info,
        'polylines': polylines,
        'gcs_params': asdict(params_to_use)
    }

def _nose_pa_deg_from_lonlat(lasco_map, lon_deg: float, lat_deg: float) -> float:
    """HGS (lon,lat) の nose 方向を LASCO 観測者の HPC に投影し、位置角（度, 北=0, 反時計廻り）を返す。"""
    import numpy as np
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    from sunpy.coordinates import frames as fr
    hgs = SkyCoord(lon_deg*u.deg, lat_deg*u.deg, 1.0*u.R_sun,
                   frame=fr.HeliographicStonyhurst(obstime=lasco_map.date))
    hpc = hgs.transform_to(fr.Helioprojective(observer=lasco_map.observer_coordinate,
                                              obstime=lasco_map.date))
    x, y = hpc.Tx.to_value(u.arcsec), hpc.Ty.to_value(u.arcsec)
    pa = (np.degrees(np.arctan2(x, y)) + 360.0) % 360.0  # 北=0°, 東=+90°
    return pa

def _sample_radial_profile_along_pa(lasco_map, pa_deg: float,
                                    rmin_rsun=2.0, rmax_rsun=6.0, nr=800) -> tuple:
    """LASCO 差分画像で、指定 PA の放射プロファイル I(r) を取得。戻り値：(r_rsun, I)。"""
    import numpy as np
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    from sunpy.coordinates import frames as fr

    rsun_arc = lasco_map.rsun_obs.to_value(u.arcsec)
    r_arc = np.linspace(rmin_rsun*rsun_arc, rmax_rsun*rsun_arc, nr)
    # 中心(0,0) からの HPC 座標（arcsec）
    th = np.radians(pa_deg)
    x_arc = r_arc * np.sin(th)
    y_arc = r_arc * np.cos(th)
    # SkyCoord → pixel
    hpc = SkyCoord(x_arc*u.arcsec, y_arc*u.arcsec,
                   frame=fr.Helioprojective(observer=lasco_map.observer_coordinate,
                                            obstime=lasco_map.date))
    xp, yp = lasco_map.world_to_pixel(hpc)
    xp, yp = xp.value, yp.value

    # バイリニアでサンプリング（scipy なし）
    data = lasco_map.data.astype(float)
    h, w = data.shape
    x0 = np.clip(np.floor(xp).astype(int), 0, w-2)
    y0 = np.clip(np.floor(yp).astype(int), 0, h-2)
    dx = xp - x0; dy = yp - y0
    I = ((1-dx)*(1-dy)*data[y0, x0] +
         dx*(1-dy)*data[y0, x0+1] +
         (1-dx)*dy*data[y0+1, x0] +
         dx*dy*data[y0+1, x0+1])
    return (r_arc/rsun_arc, I)

def _find_front_radius_rsun(r_rsun, I, smooth=5) -> float:
    """I(r) の前縁半径を 1D 勾配ピークで推定（簡易）。"""
    import numpy as np
    from numpy.lib.stride_tricks import sliding_window_view
    if smooth>1 and len(I)>=smooth:
        I = sliding_window_view(I, smooth).mean(axis=-1)
        r_rsun = r_rsun[(smooth//2):(-(smooth//2)) or None]
    # 正の勾配ピーク（ベース差分で明縁が正のとき）
    dI = np.gradient(I, r_rsun)
    k = np.argmax(dI)  # 必要に応じて np.argmax(np.abs(dI))
    return float(r_rsun[k])

def _project_apex_radius_arcsec(lasco_map, gcs_params, h_rsun: float) -> float:
    """与えた h で apex を HPC に投影し、中心からの見かけ半径（arcsec）を返す。"""
    import numpy as np
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    from sunpy.coordinates import frames as fr
    # apex は nose 方向 (lon,lat) に距離 h
    hgs = SkyCoord(gcs_params.lon_deg*u.deg, gcs_params.lat_deg*u.deg,
                   h_rsun*u.R_sun,
                   frame=fr.HeliographicStonyhurst(obstime=lasco_map.date))
    hpc = hgs.transform_to(fr.Helioprojective(observer=lasco_map.observer_coordinate,
                                              obstime=lasco_map.date))
    x, y = hpc.Tx.to_value(u.arcsec), hpc.Ty.to_value(u.arcsec)
    return float((x**2 + y**2)**0.5)

def _project_apex_xy_arcsec(lasco_map, lon_deg: float, lat_deg: float, h_rsun: float):
    """(lon,lat,h) の apex を HPC に投影し、(x,y)[arcsec], r[arcsec], PA[deg] を返す。"""
    import numpy as np
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    from sunpy.coordinates import frames as fr
    hgs = SkyCoord(lon=lon_deg*u.deg, lat=lat_deg*u.deg, radius=h_rsun*u.R_sun,
                   frame=fr.HeliographicStonyhurst(obstime=lasco_map.date))
    hpc = hgs.transform_to(fr.Helioprojective(observer=lasco_map.observer_coordinate,
                                              obstime=lasco_map.date))
    x = hpc.Tx.to_value(u.arcsec); y = hpc.Ty.to_value(u.arcsec)
    r = float(np.hypot(x, y))
    pa = float((np.degrees(np.arctan2(x, y)) + 360.0) % 360.0)   # 北=0°, 反時計回り
    return float(x), float(y), r, pa


def _detect_nose_pa_and_radius(lasco_map, pa_step_deg: float = 1.0) -> tuple:
    """
    0..360° を走査し、前縁の勾配ピークが最も強い PA と、その半径 r_obs[Rsun] を返す。
    画像内の NaN/Inf に頑健な実装。
    """
    import numpy as np
    from numpy.lib.stride_tricks import sliding_window_view

    best_pa, best_r, best_score = None, None, -np.inf

    for pa in np.arange(0.0, 360.0, float(pa_step_deg)):
        r_rsun, I = _sample_radial_profile_along_pa(lasco_map, pa)

        r = np.asarray(r_rsun, dtype=float)
        J = np.asarray(I, dtype=float)

        # 有限値のみを使用（NaN/Inf を落とす）
        m = np.isfinite(r) & np.isfinite(J)
        if m.sum() < 4:
            continue
        r = r[m]
        J = J[m]

        # 軽い移動平均で平滑化（NaN を作らない）
        if J.size >= 4:
            J_s = sliding_window_view(J, 7).mean(axis=-1)
            r_s = r[(7 // 2): (-(7 // 2)) or None]
        else:
            J_s, r_s = J, r

        # 勾配（NaN はこの時点で存在しないはずだが念のため無視）
        dI = np.gradient(J_s, r_s)
        if not np.any(np.isfinite(dI)):
            continue
        # 勾配最大の場所（明縁を想定）。NaN は除外して探索。
        k = int(np.nanargmax(dI))
        score = float(dI[k])
        if not np.isfinite(score):
            continue

        r_obs = float(r_s[k])
        if score > best_score:
            best_pa, best_r, best_score = float(pa), r_obs, score

    return best_pa, best_r


def pa_to_hgs_lonlat(pa_deg: float, lasco_map) -> tuple[float, float]:
    """
    画像平面上での位置角（PA）を、太陽物理座標（HGS）の経度・緯度に変換する。
    CMEが太陽の縁（リム）から発生したと仮定して計算する。
    """
    from sunpy.coordinates import frames as fr

    pa_rad = np.deg2rad(pa_deg)
    
    # PAは天球に投影されたHPC座標系での角度。太陽リム（半径=1Rs）上の点として座標を定義。
    # PAは北（Y軸）から反時計回りなので、X = r*sin(PA), Y = r*cos(PA) となる。
    hpc_coord = SkyCoord(
        Tx=1 * u.R_sun * np.sin(pa_rad),
        Ty=1 * u.R_sun * np.cos(pa_rad),
        frame=fr.Helioprojective(observer=lasco_map.observer_coordinate, obstime=lasco_map.date)
    )
    
    # HPC座標をHGS座標（経度・緯度）に変換
    hgs_coord = hpc_coord.transform_to(fr.HeliographicStonyhurst(obstime=lasco_map.date))
    
    lon = hgs_coord.lon.to_value(u.deg)
    lat = hgs_coord.lat.to_value(u.deg)
    
    return lon, lat
