"""
gcs_overlay.py
--------------
Overlay a GCS wireframe (generated by gcs_geometry) on the user's existing
composite coronagraph plot created by `create_single_diff_image(ax, time_str)`.

The overlay uses SunPy's coordinate frames to project 3D HGS points to
Helioprojective coordinates *with the LASCO map's observer*, then converts
arcsec -> Rsun -> pixels using the LASCO scale embedded in the user's composite.
"""
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional
import sys
import numpy as np
import matplotlib.pyplot as plt
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.time import Time

# We import only our minimal geometry helper
from .gcs_geometry import GCSParams, sample_gcs_wireframe_points

# SunPy frames imports are inside functions to avoid import-time issues if SunPy is not present.
def _to_hpc_arcsec_for_lasco(lasco_map, pts_hgs: np.ndarray, obstime: Time):
    """
    Convert Nx3 array of HGS Cartesian (Rsun) points to HPC arcsec for the LASCO observer.
    """
    import numpy as np
    from sunpy.coordinates import frames

    X, Y, Z = pts_hgs[:,0], pts_hgs[:,1], pts_hgs[:,2]
    r = np.sqrt(X*X + Y*Y + Z*Z)

    # Convert to spherical (lon, lat) in HGS
    lon = np.arctan2(Y, X) * u.rad
    lat = np.arcsin(Z / np.where(r>0, r, 1.0)) * u.rad
    radius = r * u.R_sun

    hgs = SkyCoord(lon=lon, lat=lat, radius=radius,
                   frame=frames.HeliographicStonyhurst,
                   obstime=obstime)

    # Transform to HPC using LASCO map's observer and obstime
    hpc = hgs.transform_to(
        frames.Helioprojective(
            observer=lasco_map.observer_coordinate, 
            obstime=lasco_map.date
        )
    )
    # hpc.Tx, hpc.Ty are in arcsec
    x_arcsec = hpc.Tx.to_value(u.arcsec)
    y_arcsec = hpc.Ty.to_value(u.arcsec)
    return x_arcsec, y_arcsec

def _arcsec_to_pixels_using_lasco_scale(x_arcsec: np.ndarray, y_arcsec: np.ndarray, lasco_map, p_lasco: Dict):
    """
    Convert HPC arcsec -> Rsun fraction (using LASCO's apparent solar radius) -> pixels
    relative to composite extent centered at (0,0).
    """
    rsun_arcsec = lasco_map.rsun_obs.to_value(u.arcsec)
    xr = x_arcsec / rsun_arcsec   # in Rsun
    yr = y_arcsec / rsun_arcsec
    scale = p_lasco['px_per_rsun']  # pixels per Rsun in the composite
    xp = xr * scale
    yp = yr * scale
    return xp, yp

def overlay_gcs_wireframe_on_axes(
    ax,
    lasco_map,
    p_lasco: Dict,
    gcs_params: GCSParams,
    obstime_str: str,
    n_parallels: int = 8,
    n_meridians: int = 12,
    color: str = 'white',
    color_legs: Optional[str] = None,
    lw: float = 1.0,
    alpha: float = 0.8,
    include_legs: bool = True,
    depth_shade: bool = False,
    alpha_near: float = 1.0,
    alpha_far: float = 0.3,
    alpha_far_legs: Optional[float] = None,
    leg_depth_from_joint: bool = True,
) -> Dict[str, List[np.ndarray]]:
    """
    Core overlay function to draw the wireframe given LASCO map + scale (from the composite).
    Returns the pixel polylines used (useful for debugging or saving).
    """
    # Sample 3D HGS points (Rsun)
    obstime = Time(obstime_str)

    wire = sample_gcs_wireframe_points(
        gcs_params,
        obstime=obstime,
        n_parallels=n_parallels,
        n_meridians=n_meridians,
        include_legs=include_legs,
    )

    legend_label = gcs_params.legend_label()
    legend_assigned = False

    polylines_px = {"parallels": [], "meridians": [], "legs": []}

    # 観測者（LASCO）の HGS 単位ベクトル o_hat（Sun→Observer）
    from sunpy.coordinates import frames
    obs_hgs = lasco_map.observer_coordinate.transform_to(
        frames.HeliographicStonyhurst(obstime=lasco_map.date)
    )
    import numpy as _np
    olon = obs_hgs.lon.to_value(u.rad); olat = obs_hgs.lat.to_value(u.rad)
    o_hat = _np.array([_np.cos(olat)*_np.cos(olon),
                       _np.cos(olat)*_np.sin(olon),
                       _np.sin(olat)], dtype=float)

    # Helper to project and draw
    from matplotlib.collections import LineCollection
    from matplotlib.colors import to_rgba
    def _project_and_draw(curves: List[np.ndarray], zorder: int, override_color: Optional[str] = None, is_legs: bool = False):
        nonlocal legend_assigned
        out: List[np.ndarray] = []
        for pts in curves:
            xa, ya = _to_hpc_arcsec_for_lasco(lasco_map, pts, obstime)
            xp, yp = _arcsec_to_pixels_using_lasco_scale(xa, ya, lasco_map, p_lasco)
            label = legend_label if (legend_label and not legend_assigned) else None
            
            use_color = override_color or color
            if not depth_shade:
                line_handles = ax.plot(xp, yp, color=use_color, lw=lw, alpha=alpha, zorder=zorder, label=label)
            else:
                # --- LOS 深度で alpha を連続変化 ---
                d = pts @ o_hat                   # Sun→Obs 方向成分（Rsun）
                dm = 0.5 * (d[:-1] + d[1:])       # 線分中点の深度
                if is_legs and leg_depth_from_joint:
                    # 脚：トーラス接続点（半径の大きい端）を基準に相対深度でフェード
                    import numpy as _np
                    radii = _np.sqrt((_np.asarray(pts) ** 2).sum(axis=1))
                    end0, end1 = 0, len(pts) - 1
                    joint_idx = int(end0 if radii[end0] >= radii[end1] else end1)
                    d0 = d[joint_idx]
                    rel = _np.abs(dm - d0)                 # 接続点からの離れ具合
                    rmax = rel.max() if rel.size and rel.max() > 0 else 1.0
                    w = 1.0 - (rel / rmax)                 # 接続点が 1.0, 遠ざかるほど 0.0
                else:
                    dmin, dmax = dm.min(), dm.max()
                    rng = (dmax - dmin) if (dmax > dmin) else 1.0
                    w = (dm - dmin) / rng                  # 0..1
                afar = (alpha_far_legs if (is_legs and alpha_far_legs is not None) else alpha_far)
                alphas = alpha_far + (alpha_near - afar) * w
                # 線分集合を作成
                import numpy as _np
                segs = _np.stack(
                    [_np.column_stack([xp[:-1], yp[:-1]]), _np.column_stack([xp[1:], yp[1:]])],
                    axis=1,
                )
                base = to_rgba(use_color)
                cols = [(base[0], base[1], base[2], float(a)) for a in alphas]
                lc = LineCollection(segs, colors=cols, linewidths=lw, zorder=zorder, label=label)
                ax.add_collection(lc)
                line_handles = [lc]
            if label and line_handles:
                legend_assigned = True
            out.append(np.column_stack([xp, yp]))
        return out
     
    polylines_px["parallels"] = _project_and_draw(wire["parallels"], zorder=5, override_color=None, is_legs=False)
    polylines_px["meridians"] = _project_and_draw(wire["meridians"], zorder=5, override_color=None, is_legs=False)
    if include_legs and len(wire["legs"])>0:
        polylines_px["legs"] = _project_and_draw(wire["legs"], zorder=6, override_color=(color_legs or color), is_legs=True)

    if legend_assigned:
        handles, labels = ax.get_legend_handles_labels()
        if labels:
            ax.legend(handles, labels)

    return polylines_px

def overlay_gcs_on_composite(
    ax,
    target_time_str: str,
    gcs_params: GCSParams,
    n_parallels: int = 8,
    n_meridians: int = 12,
    color: str = 'white',
    color_legs: Optional[str] = None,
    lw: float = 1.0,
    alpha: float = 0.8,
    include_legs: bool = True,
    depth_shade: bool = False,
    alpha_near: float = 1.0,
    alpha_far: float = 0.3,
    alpha_far_legs: Optional[float] = None,
    leg_depth_from_joint: bool = True,
) -> dict:
    """
    Convenience function:
      - Calls user's create_single_diff_image(ax, target_time_str)
      - Overlays the GCS wireframe using LASCO geometry from that composite
      - Returns a dict with:
          {
            'base': <return of create_single_diff_image>,
            'polylines': <pixel space polylines dict>
          }
    """
    # Import lazily to avoid pulling user config on import
    from integrated_analysis import create_single_diff_image

    # Patch Horizons lookup to tolerate offline execution (no network access)
    if not hasattr(overlay_gcs_on_composite, "_horizons_patched"):
        from sunpy.coordinates import ephemeris
        from sunpy.coordinates import frames
        from astropy.coordinates import SkyCoord
        from astropy import units as u
        from requests.exceptions import RequestException

        original_get_horizons = ephemeris.get_horizons_coord

        def _get_horizons_with_fallback(target, obstime, *args, **kwargs):
            try:
                return original_get_horizons(target, obstime, *args, **kwargs)
            except RequestException:
                pass
            except Exception as exc:  # pragma: no cover - protective fallback
                if "Name or service not known" not in str(exc):
                    raise
            target_upper = str(target).upper()
            if target_upper == 'SOHO':
                return SkyCoord(
                    lon=0.0 * u.deg,
                    lat=0.0 * u.deg,
                    radius=1.0 * u.AU,
                    frame=frames.HeliographicStonyhurst,
                    obstime=obstime,
                    observer='earth',
                )
            return original_get_horizons(target, obstime, *args, **kwargs)

        ephemeris.get_horizons_coord = _get_horizons_with_fallback
        module_integrated = sys.modules.get('integrated_analysis')
        if module_integrated is not None:
            module_integrated.get_horizons_coord = _get_horizons_with_fallback
        overlay_gcs_on_composite._horizons_patched = True

    base_info = create_single_diff_image(ax, target_time_str)
    lasco_map = base_info['lasco_map']
    p_lasco   = base_info['params_lasco']

    polylines = overlay_gcs_wireframe_on_axes(
        ax, lasco_map, p_lasco, gcs_params, obstime_str=target_time_str,
        n_parallels=n_parallels, n_meridians=n_meridians,
        color=color, color_legs=color_legs, lw=lw, alpha=alpha, include_legs=include_legs,
        depth_shade=depth_shade, alpha_near=alpha_near, alpha_far=alpha_far, leg_depth_from_joint=leg_depth_from_joint
    )
    return {'base': base_info, 'polylines': polylines}
